export const site = {
  name: "lixian.online",
  domain: "lixian.online",
  url: "https://lixian.online",
  description: "在线搞定离线包",
  keywords: [
    "开发工具",
    "下载",
    "VSCode",
    "Chrome",
    "Edge",
    "Docker",
    "Microsoft Store",
    "离线安装包",
    "开发者工具",
  ],
  author: "lixian.online",
  userAgent: "Mozilla/5.0 (compatible; lixian.online/1.0)",
  github: "https://github.com/liaoguoyin/lixian.online",
} as const;
